export const TYPES = {
  USER_REQUEST: "USER__REQUEST",
  USER_SUCCESS: "USER__SUCCESS",
  USER_FAILURE: "USER__FAILURE",
  USER_RESET_NOTIFICATION: "USER__RESET_NOTIFICATION",
  TASKS_REQUEST: "TASKS__REQUEST",
  TASKS_SUCCESS: "TASKS__SUCCESS",
  TASKS_FAILURE: "TASKS__FAILURE",
  TASKS_RESET_NOTIFICATION: "TASKS__RESET_NOTIFICATION",
}
