export const TYPES = {
  USER_REQUEST: "USER__REQUEST",
  USER_SUCCESS: "USER__SUCCESS",
  USER_FAILURE: "USER_FAILURE",
  USER_RESET_NOTIFICATION: "USER_RESET_NOTIFICATION",
  TASKS_REQUEST: "TASKS_REQUEST",
  TASKS_SUCCESS: "TASKS_SUCCESS",
  TASKS_FAILURE: "TASKS_FAILURE",
  TASKS_RESET_NOTIFICATION: "TASKS_RESET_NOTIFICATION",
  TASKS_RESET_STATE: "TASKS_RESET_STATE",
}
